/* @generated */
digraph cfg {
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_1" [label="1: Start void AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstructor()\nFormals:  this:org.junit.AssumptionViolatedExceptionTest*\nLocals:  $irvar1:void $irvar0:void e:org.junit.AssumptionViolatedException* cause:java.lang.Throwable*\nAnnotation: <_org.junit.Test> void AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstructor()() \n  " color=yellow style=filled]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_1" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_4" ;
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_2" [label="2: Exit void AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstructor() \n  " color=yellow style=filled]
	

"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [label="3:  exceptions sink \n   NULLIFY(&$irvar0); [line 117]\n  NULLIFY(&cause); [line 117]\n  NULLIFY(&$irvar1); [line 117]\n  NULLIFY(&e); [line 117]\n  EXIT_SCOPE($irvar0,cause,$irvar1,e); [line 117]\n  APPLY_ABSTRACTION; [line 117]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_2" ;
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_4" [label="4:  Call Exception.<init>() \n   n$0=_fun___new(sizeof(t=java.lang.Exception):java.lang.Exception*) [line 114]\n  n$1=_fun_Exception.<init>()(n$0:java.lang.Exception*) [line 114]\n  *&cause:java.lang.Exception*=n$0 [line 114]\n  EXIT_SCOPE(n$0,n$1); [line 114]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_4" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_5" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_4" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_5" [label="5:  Call AssumptionViolatedException.<init>(String,Throwable) \n   n$2=_fun___new(sizeof(t=org.junit.AssumptionViolatedException):org.junit.AssumptionViolatedException*) [line 115]\n  n$3=*&cause:java.lang.Exception* [line 115]\n  n$4=_fun_AssumptionViolatedException.<init>(String,Throwable)(n$2:org.junit.AssumptionViolatedException*,\"invalid number\":java.lang.Object*,n$3:java.lang.Exception*) [line 115]\n  *&e:org.junit.AssumptionViolatedException*=n$2 [line 115]\n  EXIT_SCOPE(n$2,n$3,n$4); [line 115]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_5" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_6" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_5" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_6" [label="6:  Call Throwable AssumptionViolatedException.getCause() \n   n$5=*&e:org.junit.AssumptionViolatedException* [line 116]\n  _=*n$5:org.junit.AssumptionViolatedException*(root org.junit.AssumptionViolatedException) [line 116]\n  n$7=_fun_Throwable AssumptionViolatedException.getCause()(n$5:org.junit.AssumptionViolatedException*) virtual [line 116]\n  *&$irvar0:java.lang.Throwable*=n$7 [line 116]\n  NULLIFY(&e); [line 116]\n  EXIT_SCOPE(_,n$5,n$7,e); [line 116]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_6" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_7" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_6" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_7" [label="7:  Call Matcher CoreMatchers.is(Object) \n   n$8=*&cause:java.lang.Exception* [line 116]\n  n$9=_fun_Matcher CoreMatchers.is(Object)(n$8:java.lang.Exception*) [line 116]\n  *&$irvar1:org.hamcrest.Matcher*=n$9 [line 116]\n  NULLIFY(&cause); [line 116]\n  EXIT_SCOPE(n$8,n$9,cause); [line 116]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_7" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_8" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_7" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_8" [label="8:  Call void MatcherAssert.assertThat(Object,Matcher) \n   n$10=*&$irvar0:java.lang.Throwable* [line 116]\n  n$11=*&$irvar1:org.hamcrest.Matcher* [line 116]\n  n$12=_fun_void MatcherAssert.assertThat(Object,Matcher)(n$10:java.lang.Throwable*,n$11:org.hamcrest.Matcher*) [line 116]\n  NULLIFY(&$irvar0); [line 116]\n  NULLIFY(&$irvar1); [line 116]\n  EXIT_SCOPE(n$10,n$11,n$12,$irvar0,$irvar1); [line 116]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_8" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_9" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_8" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
"org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_9" [label="9:  method_body \n   APPLY_ABSTRACTION; [line 117]\n " shape="box"]
	

	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_9" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_2" ;
	 "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_9" -> "org.junit.AssumptionViolatedExceptionTest.canSetCauseWithInstanceCreatedWithExplicitThrowableConstru.194dc1bd6da80a5e81c032a2f4a00578_3" [color="red" ];
}
