/* @generated */
digraph cfg {
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_1" [label="1: Start void ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause()\nFormals:  this:org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause*\nLocals:  $irvar4:void $irvar3:void $irvar2:void $irvar1:void $irvar0:void\nAnnotation: <_org.junit.Test> void ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause()() \n  " color=yellow style=filled]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_1" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_4" ;
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_2" [label="2: Exit void ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause() \n  " color=yellow style=filled]
	

"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [label="3:  exceptions sink \n   NULLIFY(&$irvar3); [line 331]\n  NULLIFY(&$irvar4); [line 331]\n  NULLIFY(&$irvar0); [line 331]\n  NULLIFY(&$irvar1); [line 331]\n  NULLIFY(&$irvar2); [line 331]\n  EXIT_SCOPE($irvar3,$irvar4,$irvar0,$irvar1,$irvar2); [line 331]\n  APPLY_ABSTRACTION; [line 331]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_2" ;
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_4" [label="4:  Call void ExpectedException.expect(Class) \n   n$0=*&this:org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause* [line 327]\n  n$1=*n$0.thrown:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause) [line 327]\n  _=*n$1:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedException) [line 327]\n  n$3=_fun_void ExpectedException.expect(Class)(n$1:org.junit.rules.ExpectedException*,java.lang.IllegalArgumentException:java.lang.Object*) virtual [line 327]\n  EXIT_SCOPE(_,n$0,n$1,n$3); [line 327]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_4" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_5" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_4" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_5" [label="5:  Call void ExpectedException.expectMessage(String) \n   n$4=*&this:org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause* [line 328]\n  n$5=*n$4.thrown:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause) [line 328]\n  _=*n$5:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedException) [line 328]\n  n$7=_fun_void ExpectedException.expectMessage(String)(n$5:org.junit.rules.ExpectedException*,\"Ack!\":java.lang.Object*) virtual [line 328]\n  EXIT_SCOPE(_,n$4,n$5,n$7); [line 328]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_5" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_6" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_5" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_6" [label="6:  method_body \n   n$8=*&this:org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause* [line 329]\n  n$9=*n$8.thrown:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause) [line 329]\n  *&$irvar0:org.junit.rules.ExpectedException*=n$9 [line 329]\n  NULLIFY(&this); [line 329]\n  EXIT_SCOPE(n$8,n$9,this); [line 329]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_6" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_7" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_6" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_7" [label="7:  Call NullPointerException.<init>(String) \n   n$10=_fun___new(sizeof(t=java.lang.NullPointerException):java.lang.NullPointerException*) [line 329]\n  n$11=_fun_NullPointerException.<init>(String)(n$10:java.lang.NullPointerException*,\"expected cause\":java.lang.Object*) [line 329]\n  *&$irvar1:java.lang.NullPointerException*=n$10 [line 329]\n  EXIT_SCOPE(n$10,n$11); [line 329]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_7" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_8" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_7" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_8" [label="8:  Call Matcher CoreMatchers.is(Object) \n   n$12=*&$irvar1:java.lang.NullPointerException* [line 329]\n  n$13=_fun_Matcher CoreMatchers.is(Object)(n$12:java.lang.NullPointerException*) [line 329]\n  *&$irvar2:org.hamcrest.Matcher*=n$13 [line 329]\n  NULLIFY(&$irvar1); [line 329]\n  EXIT_SCOPE(n$12,n$13,$irvar1); [line 329]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_8" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_9" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_8" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_9" [label="9:  Call void ExpectedException.expectCause(Matcher) \n   n$14=*&$irvar0:org.junit.rules.ExpectedException* [line 329]\n  _=*n$14:org.junit.rules.ExpectedException*(root org.junit.rules.ExpectedException) [line 329]\n  n$16=*&$irvar2:org.hamcrest.Matcher* [line 329]\n  n$17=_fun_void ExpectedException.expectCause(Matcher)(n$14:org.junit.rules.ExpectedException*,n$16:org.hamcrest.Matcher*) virtual [line 329]\n  NULLIFY(&$irvar0); [line 329]\n  NULLIFY(&$irvar2); [line 329]\n  EXIT_SCOPE(_,n$14,n$16,n$17,$irvar0,$irvar2); [line 329]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_9" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_10" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_9" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_10" [label="10:  Call NullPointerException.<init>(String) \n   n$18=_fun___new(sizeof(t=java.lang.NullPointerException):java.lang.NullPointerException*) [line 331]\n  n$19=_fun_NullPointerException.<init>(String)(n$18:java.lang.NullPointerException*,\"an unexpected cause\":java.lang.Object*) [line 331]\n  *&$irvar3:java.lang.NullPointerException*=n$18 [line 331]\n  EXIT_SCOPE(n$18,n$19); [line 331]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_10" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_11" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_10" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_11" [label="11:  Call IllegalArgumentException.<init>(String,Throwable) \n   n$20=_fun___new(sizeof(t=java.lang.IllegalArgumentException):java.lang.IllegalArgumentException*) [line 331]\n  n$21=*&$irvar3:java.lang.NullPointerException* [line 331]\n  n$22=_fun_IllegalArgumentException.<init>(String,Throwable)(n$20:java.lang.IllegalArgumentException*,\"Ack!\":java.lang.Object*,n$21:java.lang.NullPointerException*) [line 331]\n  *&$irvar4:java.lang.IllegalArgumentException*=n$20 [line 331]\n  NULLIFY(&$irvar3); [line 331]\n  EXIT_SCOPE(n$20,n$21,n$22,$irvar3); [line 331]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_11" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_12" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_11" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
"org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_12" [label="12:  throw \n   n$23=*&$irvar4:java.lang.IllegalArgumentException* [line 331]\n  *&return:void=EXN n$23 [line 331]\n  NULLIFY(&$irvar4); [line 331]\n  EXIT_SCOPE(n$23,$irvar4); [line 331]\n  APPLY_ABSTRACTION; [line 331]\n " shape="box"]
	

	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_12" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_2" ;
	 "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_12" -> "org.junit.rules.ExpectedExceptionTest$ThrowUnexpectedCause.throwWithCause():void.3875b148acb599671c55350c4805c27d_3" [color="red" ];
}
