<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>org.junit.rules.ErrorCollector.checkSucceeds(org.junit.rules.ErrorCollectorTest$CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
body { background-color:#fff; color:#000; font-family:Helvetica, sans-serif; font-size:10pt }
h1 { font-size:14pt }
.code { border-collapse:collapse; width:100%; font-family: "Andale Mono", monospace; font-size:10pt; line-height: 1.2em }
.color_black { color: black }
.color_blue { color: blue }
.color_green { color: green }
.color_orange { color: orange }
.color_red { color: red }
.line { border-left: 3px solid #ccc; padding-left: 1ex; white-space: pre; }
.msg { background-color:#fff8b4; color:#000; float:left; font-family:Helvetica, sans-serif; font-size: smaller; font-weight: bold; margin-bottom:10px; margin-top:10px; max-width:60em; padding:0.5em 1ex 0.5em 1ex; -webkit-border-radius:5px; -webkit-box-shadow:1px 1px 7px #000; white-space: pre-wrap; word-wrap: break-word; }
.num { background-color:#eee; color:#444; font-size: smaller; padding-right:2ex; text-align:right; width:2.5em; }
.dangling { background-color:white; color: gray; }
.visited { background-color:LemonChiffon; color: darkmagenta; }
.tooltip { display: none; background-color:#FFF0F0; border: 2px solid #F00; font-weight: normal; left:10em; padding: 2px; position: absolute; top: -1em; -webkit-border-radius:5px; -webkit-box-shadow:1px 1px 7px #000; z-index: 1}
.with_tooltip { position: relative; }
.with_tooltip:hover .tooltip, .visited:hover .tooltip { display: block; }
</style>
</head>
<body>
<center><h1>Cfg Node <a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">10</a></h1></center>PROC: <a href="./../org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e.html">Object ErrorCollector.checkSucceeds(ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1)</a> LINE: <a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>
<br>PREDS:
<a href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node9.html"><span class='visited with_tooltip'>N_9<span class='tooltip'>node9 preds:8 succs:10 exn:5 </span></span></a><br>SUCCS:
<a href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node11.html"><span class='visited with_tooltip'>N_11<span class='tooltip'>node11 preds:10 succs:2 exn:5 </span></span></a><br>EXN:
<a href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node5.html"><span class='visited with_tooltip'>N_5<span class='tooltip'>node5 preds:17 succs:2 exn:2 </span></span></a><br>
<LISTING class='color_green'>n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94];
_=*n$11:org.junit.rules.ErrorCollector [line 94];
n$13=*&amp;error:java.lang.AssertionError* [line 94];
n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94];
</LISTING>
<hr width="100%">
<a name="session6" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session6">node10#session6</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [compute pre] liveness 10
<LISTING class='color_black'>JOIN

LEFT:   normal:{ }, exn:{ }
RIGHT:  normal:{ }, exn:{ }
RESULT: normal:{ }, exn:{ }

</LISTING>
<hr width="100%">
<a name="session7" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session7">node10#session7</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] liveness 10
<LISTING class='color_black'>PRE STATE:
normal:{ }, exn:{ }

INSTR=  n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94]; 

STATE:
normal:{ n$11, n$13 }, exn:{ }

INSTR=  n$13=*&amp;error:java.lang.AssertionError* [line 94]; 

STATE:
normal:{ n$11, error }, exn:{ }

INSTR=  _=*n$11:org.junit.rules.ErrorCollector [line 94]; 

STATE UNCHANGED

INSTR=  n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94]; 

STATE:
normal:{ error, this }, exn:{ }

</LISTING>
<hr width="100%">
<a name="session49" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session49">node10#session49</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [compute pre] nullify
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session50" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session50">node10#session50</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] nullify
<LISTING class='color_black'>PRE STATE:
(normal:{ error }, exn:{ },normal:{ _, n$7, n$9, n$10, $irvar1, e }, exn:{ })

INSTR=  n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94]; 

STATE:
(normal:{ n$11, error }, exn:{ },
normal:{ _, n$7, n$9, n$10, $irvar1, e }, exn:{ })

INSTR=  _=*n$11:org.junit.rules.ErrorCollector [line 94]; 

STATE:
(normal:{ _, n$11, error }, exn:{ },
normal:{ _, n$7, n$9, n$10, $irvar1, e }, exn:{ })

INSTR=  n$13=*&amp;error:java.lang.AssertionError* [line 94]; 

STATE:
(normal:{ _, n$11, n$13, error }, exn:{ },
normal:{ _, n$7, n$9, n$10, $irvar1, e }, exn:{ })

INSTR=  n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94]; 

STATE:
(normal:{ }, exn:{ },normal:{ _, n$11, n$13, n$14, error, this }, exn:{ })

</LISTING>
<hr width="100%">
<a name="session109" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session109">node10#session109</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session110" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session110">node10#session110</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session111" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session111">node10#session111</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session112" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session112">node10#session112</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'>virtual call void ErrorCollector.addError(Throwable) 
</LISTING>
<hr width="100%">
<a name="session113" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session113">node10#session113</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session114" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session114">node10#session114</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session115" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session115">node10#session115</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session9" href="./../nodes/org.junit.rules.ErrorCollector.checkSucceeds%28org.junit.rules.ErrorCollectorTest%24CheckCallableThatThr.3cf67ad5a215a2e1984ee77b4479bc6e_node10.html#session9">node10#session9</a>(<a href="./../../ErrorCollector.java.572ca47a97c2ffbb3a38d177cca6c52b.html#LINE94">94</a>) biabduction
<LISTING class='color_black'>**** [FP:Pending] Object ErrorCollector.checkSucceeds(ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1) Node: 10, Procedure: Object ErrorCollector.checkSucceeds(ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1), Todo: 1 ****
  PROP 1 of 1:
  <span class='color_blue'><span class='color_red'>_t$2 != 0</span>; <span class='color_red'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(_t$2)</span>; <span class='color_red'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_red'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_red'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_red'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (_t$3)</span> ;
  <span class='color_red'>error = _t$1<span class='color_orange'>update:92</span>:java.lang.AssertionError*</span>; <span class='color_red'>CatchVar31 = _t$0<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_red'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_red'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_red'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_red'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_red'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_red'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_red'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_red'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
  <span class='color_red'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_red'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>
  [footprint
     <span class='color_red'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_red'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_red'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_red'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
     <span class='color_red'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>  ]</span>
  .... Instructions: ....
  <span class='color_green'>n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94];
  _=*n$11:org.junit.rules.ErrorCollector [line 94];
  n$13=*&amp;error:java.lang.AssertionError* [line 94];
  n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94];
  NULLIFY(&amp;error); [line 94];
  NULLIFY(&amp;this); [line 94];
  EXIT_SCOPE(_,n$11,n$13,n$14,error,this); [line 94];
  </span>
  
  Processing prop 1/1
    Instruction <span class='color_green'>n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94]</span>
    in vpath_find exp:n$125
    vpath_find: cannot find n$125
    in vpath_find exp:n$123
    vpath_find: found error :java.lang.AssertionError*
    .... Rearrangement Start ....
    Exp: &amp;this
    Prop:
    <span class='color_blue'>n$125 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$125); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$126) ;
    error = n$123<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$124<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )  ]</span>
    
    in prop_iter_extend_ptsto lexp: &amp;this
    prop before:
    <span class='color_blue'>n$125 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$125); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$126) ;
    error = n$123<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$124<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )  ]</span>
    
    
    prop list after:
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>n$125 != 0</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$125)</span>; <span class='color_blue'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$126)</span> ;
    <span class='color_blue'>error = n$123<span class='color_orange'>update:92</span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = n$124<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_blue'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>  ]</span>
    
    
    
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>n$11 = old_this</span> ;
    <span class='color_blue'>_t$2 != 0</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(_t$2)</span>; <span class='color_blue'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (_t$3)</span> ;
    <span class='color_blue'>error = _t$1<span class='color_orange'>update:92</span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = _t$0<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_blue'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>_=*n$11:org.junit.rules.ErrorCollector [line 94]</span>
    in vpath_find exp:n$129
    vpath_find: cannot find n$129
    in vpath_find exp:n$127
    vpath_find: found error :java.lang.AssertionError*
    .... Rearrangement Start ....
    Exp: @f$0
    Prop:
    <span class='color_blue'>n$11 = old_this ;
    n$129 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$129); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$130) ;
    error = n$127<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$128<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )  ]</span>
    
    ++++ Adding footprint frame
    <span class='color_blue'>@f$0|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>
    
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>n$11 = old_this</span> ;
    <span class='color_blue'>_t$2 != 0</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(_t$2)</span>; <span class='color_blue'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (_t$3)</span> ;
    <span class='color_blue'>error = _t$1<span class='color_orange'>update:92</span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = _t$0<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_blue'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_red'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_red'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>n$13=*&amp;error:java.lang.AssertionError* [line 94]</span>
    in vpath_find exp:n$133
    vpath_find: cannot find n$133
    in vpath_find exp:n$131
    vpath_find: found error :java.lang.AssertionError*
    .... Rearrangement Start ....
    Exp: &amp;error
    Prop:
    <span class='color_blue'>n$11 = old_this ;
    n$133 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$133); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$134) ;
    error = n$131<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$132<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    
    in prop_iter_extend_ptsto lexp: &amp;error
    prop before:
    <span class='color_blue'>n$11 = old_this ;
    n$133 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$133); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$134) ;
    error = n$131<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$132<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    
    
    prop list after:
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>n$11 = old_this</span> ;
    <span class='color_blue'>n$133 != 0</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$133)</span>; <span class='color_blue'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$134)</span> ;
    <span class='color_blue'>error = n$131<span class='color_orange'>update:92</span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = n$132<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_blue'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>  ]</span>
    
    
    
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>n$11 = old_this</span> ;
    <span class='color_blue'>_t$1 != 0</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(_t$1)</span>; <span class='color_red'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (_t$2)</span> ;
    <span class='color_blue'>error = <span class='color_red'>n$13<span class='color_orange'>update:92</span></span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = _t$0<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = null<span class='color_orange'>update:91</span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_red'>error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94]</span>
    in vpath_find exp:n$136
    vpath_find: cannot find n$136
    in vpath_find exp:n$13
    vpath_find: found error :java.lang.AssertionError*
    Found 3 specs for function org.junit.rules.ErrorCollector.addError(java.lang.AssertionError):void
    START EXECUTING SPECS FOR org.junit.rules.ErrorCollector.addError(java.lang.AssertionError):void from state
    <span class='color_blue'>n$11 = old_this ;
    n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137) ;
    error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    EXECUTING SPEC 1/3
    ACTUAL PRECONDITION =
      <span class='color_blue'>n$11 = old_this ;
      n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137) ;
      error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
      error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
      [footprint
         $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
         old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>error|callee = null<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$160<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'><span class='color_red'>MEMne &lt; new:50 &gt; <span class='color_orange'>{vpath: }</span>(_t$161)</span> ;
      <span class='color_red'>return|callee = EXN _t$161<span class='color_orange'>update:50</span>:void</span> ;
      <span class='color_red'>_t$161|->{}<span class='color_orange'>alloc</span>:java.lang.NullPointerException</span></span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      n$11 = @f$0; n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(n$13); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137)
    pi2:
      
    returns
    sub1:
      n$11 = @f$0
    sub2:
      
    Current Implication
    SUB:
      n$11 = @f$0
    <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
    error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    |-
    <span class='color_blue'>error|callee = null<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$160<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>
    
      do_imply n$13 null
        Current Implication
        SUB:
          n$11 = @f$0
        <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
        error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
        error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
        [footprint
           $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
           old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
        [SUB: 
          
        n$13 = null]
        |-
        <span class='color_blue'>this|callee = _t$160<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>
        
          do_imply @f$0 _t$160
            Final Implication
            SUB:
              n$11 = @f$0
            <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
            error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
            error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
            [footprint
               $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
               old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
            [SUB: 
              _t$160 = @f$0
            n$13 = null]
            |-
            <span class='color_blue'></span>
    Result of Abduction
      SUB:
        n$11 = @f$0
      <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
      error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
      error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
      [footprint
         $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
         old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
      [SUB: 
        _t$160 = @f$0
      n$13 = null]
      |-
      <span class='color_blue'>error|callee = null<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub )</span>
    returning TRUE
    in vpath_find exp:_t$161
    vpath_find: cannot find _t$161
      New footprint:
      n$13 = null
      Frame fld:
      
      Missing fld:
      
      Instantiated frame:
      n$13|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; @f$1|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); @f$0|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub ); &amp;error|->n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; &amp;CatchVar31|->n$135<span class='color_orange'>initial</span>:void; &amp;CatchVar7|->0<span class='color_orange'>nullify</span>:void; &amp;$irvar0|->0<span class='color_orange'>nullify</span>:void; &amp;callable|->0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); &amp;old_callable|->@f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); &amp;return|->null<span class='color_orange'>update:91</span>:java.lang.Object*; &amp;$irvar1|->0<span class='color_orange'>nullify</span>:void; &amp;this|->@f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); &amp;old_this|->@f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); &amp;e|->0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*
      Instantiated post:
      PROP 1 of 1:
      <span class='color_blue'><span class='color_red'>MEMne &lt; void ErrorCollector.addError(AssertionError):94 &gt; <span class='color_orange'>{vpath: }</span>(_t$161)</span> ;
      <span class='color_red'>return|callee = EXN _t$161<span class='color_orange'>update:94</span>:void</span> ;
      <span class='color_red'>_t$161|->{}<span class='color_orange'>alloc</span>:java.lang.NullPointerException</span></span>
      
    <span class='color_orange'>WARNING: dropping atom with non-footprint variable</span>
    n$13 = null
    ***** RESULTS FUNCTION CALL *******
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>n$11 = <span class='color_red'>old_this</span></span>; <span class='color_blue'>n$13 = null</span> ;
    <span class='color_blue'>n$136 != 0</span>; <span class='color_red'>MEMne &lt; void ErrorCollector.addError(AssertionError):94 &gt; <span class='color_orange'>{vpath: }</span>(_t$0)</span>; <span class='color_blue'>MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136)</span>; <span class='color_red'>MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(null)</span>; <span class='color_blue'>UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3)</span>; <span class='color_blue'>UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2)</span>; <span class='color_blue'>RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137)</span> ;
    <span class='color_blue'>error = <span class='color_red'>null<span class='color_orange'>update:(ncf)92</span></span>:java.lang.AssertionError*</span>; <span class='color_blue'>CatchVar31 = n$135<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>CatchVar7 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>$irvar0 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>old_callable = <span class='color_red'>@f$0<span class='color_orange'>formal</span></span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>EXN _t$0<span class='color_orange'>update:94</span></span>:java.lang.Object*</span>; <span class='color_blue'>$irvar1 = 0<span class='color_orange'>nullify</span>:void</span>; <span class='color_blue'>this = <span class='color_red'>@f$1<span class='color_orange'>formal</span></span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>old_this = <span class='color_red'>@f$1<span class='color_orange'>formal</span></span>:org.junit.rules.ErrorCollector*( sub )</span>; <span class='color_blue'>e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException*</span> ;
    <span class='color_red'>_t$0|->{}<span class='color_orange'>alloc</span>:java.lang.NullPointerException</span>; <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>; <span class='color_red'>null|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError</span>
    [footprint
       <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub )</span>; <span class='color_blue'>$RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub )</span>; <span class='color_blue'>callable = <span class='color_red'>@f$0<span class='color_orange'>formal</span></span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub )</span>; <span class='color_blue'>this = <span class='color_red'>@f$1<span class='color_orange'>formal</span></span>:org.junit.rules.ErrorCollector*( sub )</span> ;
       <span class='color_blue'>old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )</span>; <span class='color_blue'>old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>  ]</span>
    ***** END RESULTS FUNCTION CALL *******
    Prover.check_inconsistency_base: inconsistency reason [Some 0]
    Prover.check_inconsistency_base: inconsistency reason [Some 0]
    EXECUTING SPEC 2/3
    ACTUAL PRECONDITION =
      <span class='color_blue'>n$11 = old_this ;
      n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137) ;
      error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
      error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
      [footprint
         $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
         old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>error|callee != null ;
      error|callee = _t$162<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$164<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
      error|callee|->{}<span class='color_orange'>none</span>:java.lang.Throwable- {org.junit.internal.AssumptionViolatedException}(instof); _t$163|->{}<span class='color_orange'>rearrange:(z)57</span>:java.util.List( sub ); this|callee|->{errors:_t$163<span class='color_orange'>rearrange:(z)57</span>}<span class='color_orange'>rearrange:(z)57</span>:org.junit.rules.ErrorCollector( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'>error|callee != null ;
      <span class='color_red'>return|callee = _t$165<span class='color_orange'>initial</span>:void</span> ;
      error|callee|->{}<span class='color_orange'>formal</span>:java.lang.Throwable- {org.junit.internal.AssumptionViolatedException}(instof); _t$163|->{}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{errors:_t$163<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:org.junit.rules.ErrorCollector( sub )</span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      n$11 = @f$0; n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(n$13); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137)
    pi2:
      _t$162 != null
    returns
    sub1:
      n$11 = @f$0
    sub2:
      
    Current Implication
    SUB:
      n$11 = @f$0
    <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
    error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    |-
    <span class='color_blue'>error|callee = _t$162<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$164<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
    this|callee|->{errors:_t$163<span class='color_orange'>rearrange:(z)57</span>}<span class='color_orange'>rearrange:(z)57</span>:org.junit.rules.ErrorCollector( sub ); _t$163|->{}<span class='color_orange'>rearrange:(z)57</span>:java.util.List( sub ); error|callee|->{}<span class='color_orange'>none</span>:java.lang.Throwable- {org.junit.internal.AssumptionViolatedException}(instof)</span>
    
      do_imply n$13 _t$162
        Current Implication
        SUB:
          n$11 = @f$0
        <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
        error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
        error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
        [footprint
           $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
           old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
        [SUB: 
          _t$162 = n$13]
        |-
        <span class='color_blue'>this|callee = _t$164<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
        this|callee|->{errors:_t$163<span class='color_orange'>rearrange:(z)57</span>}<span class='color_orange'>rearrange:(z)57</span>:org.junit.rules.ErrorCollector( sub ); _t$163|->{}<span class='color_orange'>rearrange:(z)57</span>:java.util.List( sub ); n$13|->{}<span class='color_orange'>none</span>:java.lang.Throwable- {org.junit.internal.AssumptionViolatedException}(instof)</span>
        
          do_imply @f$0 _t$164
            Current Implication
            SUB:
              n$11 = @f$0
            <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
            error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
            error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
            [footprint
               $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
               old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
            [SUB: 
              _t$162 = n$13; _t$164 = @f$0]
            |-
            <span class='color_blue'>@f$0|->{errors:_t$163<span class='color_orange'>rearrange:(z)57</span>}<span class='color_orange'>rearrange:(z)57</span>:org.junit.rules.ErrorCollector( sub ); _t$163|->{}<span class='color_orange'>rearrange:(z)57</span>:java.util.List( sub ); n$13|->{}<span class='color_orange'>none</span>:java.lang.Throwable- {org.junit.internal.AssumptionViolatedException}(instof)</span>
            
              WARNING: footprint failed to find MISSING because: class cast exception
    EXECUTING SPEC 3/3
    ACTUAL PRECONDITION =
      <span class='color_blue'>n$11 = old_this ;
      n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137) ;
      error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
      error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
      [footprint
         $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
         old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>error|callee != null ;
      error|callee = _t$166<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$168<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
      error|callee|->{}<span class='color_orange'>none</span>:org.junit.internal.AssumptionViolatedException( sub )(instof); _t$167|->{}<span class='color_orange'>rearrange:(z)55</span>:java.util.List( sub ); this|callee|->{errors:_t$167<span class='color_orange'>rearrange:(z)55</span>}<span class='color_orange'>rearrange:(z)55</span>:org.junit.rules.ErrorCollector( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'>error|callee != null ;
      <span class='color_red'>return|callee = _t$169<span class='color_orange'>initial</span>:void</span> ;
      error|callee|->{}<span class='color_orange'>formal</span>:org.junit.internal.AssumptionViolatedException( sub )(instof); _t$167|->{}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{errors:_t$167<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:org.junit.rules.ErrorCollector( sub )</span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      n$11 = @f$0; n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(n$13); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137)
    pi2:
      _t$166 != null
    returns
    sub1:
      n$11 = @f$0
    sub2:
      
    Current Implication
    SUB:
      n$11 = @f$0
    <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error|callee); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
    error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; error|callee = n$13<span class='color_orange'>actual_precondition</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
    error|callee|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
    [footprint
       $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
       old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
    |-
    <span class='color_blue'>error|callee = _t$166<span class='color_orange'>formal</span>:java.lang.AssertionError*( sub ); this|callee = _t$168<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
    this|callee|->{errors:_t$167<span class='color_orange'>rearrange:(z)55</span>}<span class='color_orange'>rearrange:(z)55</span>:org.junit.rules.ErrorCollector( sub ); _t$167|->{}<span class='color_orange'>rearrange:(z)55</span>:java.util.List( sub ); error|callee|->{}<span class='color_orange'>none</span>:org.junit.internal.AssumptionViolatedException( sub )(instof)</span>
    
      do_imply n$13 _t$166
        Current Implication
        SUB:
          n$11 = @f$0
        <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
        error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); this|callee = @f$0<span class='color_orange'>actual_precondition</span>:org.junit.rules.ErrorCollector*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
        error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
        [footprint
           $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
           old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
        [SUB: 
          _t$166 = n$13]
        |-
        <span class='color_blue'>this|callee = _t$168<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
        this|callee|->{errors:_t$167<span class='color_orange'>rearrange:(z)55</span>}<span class='color_orange'>rearrange:(z)55</span>:org.junit.rules.ErrorCollector( sub ); _t$167|->{}<span class='color_orange'>rearrange:(z)55</span>:java.util.List( sub ); n$13|->{}<span class='color_orange'>none</span>:org.junit.internal.AssumptionViolatedException( sub )(instof)</span>
        
          do_imply @f$0 _t$168
            Current Implication
            SUB:
              n$11 = @f$0
            <span class='color_blue'>n$136 != 0; MEMne &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call():90 &gt; <span class='color_orange'>{vpath: }</span>(n$136); MEMne &lt; new:92 &gt; <span class='color_orange'>{vpath: }</span>(error); UND &lt; AssertionError.<init>(Object) &gt; :92(@f$3); UND &lt; Throwable AssertionError.initCause(AssumptionViolatedException) &gt; :93(@f$2); RET &lt; Object ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1.call() &gt; (n$137); old_this = old_this ;
            error = n$13<span class='color_orange'>update:92</span>:java.lang.AssertionError*; CatchVar31 = n$135<span class='color_orange'>initial</span>:void; CatchVar7 = 0<span class='color_orange'>nullify</span>:void; $irvar0 = 0<span class='color_orange'>nullify</span>:void; callable = 0<span class='color_orange'>nullify</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); old_callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); return = null<span class='color_orange'>update:91</span>:java.lang.Object*; $irvar1 = 0<span class='color_orange'>nullify</span>:void; this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ); e = 0<span class='color_orange'>nullify</span>:org.junit.internal.AssumptionViolatedException* ;
            error|->{}<span class='color_orange'>alloc</span>:java.lang.AssertionError; old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )
            [footprint
               $RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = @f$3<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = @f$2<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = @f$1<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = @f$0<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
               old_callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub ); old_this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub )  ]</span>
            [SUB: 
              _t$166 = n$13; _t$168 = @f$0]
            |-
            <span class='color_blue'>@f$0|->{errors:_t$167<span class='color_orange'>rearrange:(z)55</span>}<span class='color_orange'>rearrange:(z)55</span>:org.junit.rules.ErrorCollector( sub ); _t$167|->{}<span class='color_orange'>rearrange:(z)55</span>:java.util.List( sub ); n$13|->{}<span class='color_orange'>none</span>:org.junit.internal.AssumptionViolatedException( sub )(instof)</span>
            
              WARNING: footprint failed to find MISSING because: class cast exception
    exp_rv_dexp: normal var n$13
    find_normal_variable_load defining &amp;error
    exp_lv_dexp: program var &amp;error
    exp_rv_dexp: type sizeof(t=java.lang.AssertionError)
    exp_rv_dexp: type sizeof(t=java.lang.Throwable;sub_t=- {org.junit.internal.AssumptionViolatedException}(instof))
    <span class='color_red'>Failure of symbolic execution: CLASS_CAST_EXCEPTION `java.lang.AssertionError` cannot be cast to `java.lang.Throwable`  in expression `error`  in call to `addError(...)` at line 94 src/biabduction/Tabulation.ml:1289:76-83:</span>
    Precondition:
    <span class='color_blue'>$RET_java.lang.AssertionError.<init>(java.lang.Object)|abducedRetvar = val$5<span class='color_orange'>none</span>:void( sub ); $RET_java.lang.AssertionError.initCause(org.junit.internal.AssumptionViolatedException):java.lang.Throwable|abducedRetvar = val$6<span class='color_orange'>none</span>:java.lang.Throwable*( sub ); callable = val$2<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1*( sub ); this = val$3<span class='color_orange'>formal</span>:org.junit.rules.ErrorCollector*( sub ) ;
    this|->{}<span class='color_orange'>rearrange:(z)94</span>:org.junit.rules.ErrorCollector( sub ); callable|->{}<span class='color_orange'>rearrange:(z)90</span>:org.junit.rules.ErrorCollectorTest$CheckCallableThatThrowsInternalAssumptionViolatedException$1( sub )</span>
    SIL INSTR:
    <span class='color_green'>n$11=*&amp;this:org.junit.rules.ErrorCollector* [line 94];
    _=*n$11:org.junit.rules.ErrorCollector [line 94];
    n$13=*&amp;error:java.lang.AssertionError* [line 94];
    <span class='color_red'>n$14=_fun_void ErrorCollector.addError(Throwable)(n$11:org.junit.rules.ErrorCollector*,n$13:java.lang.AssertionError*) virtual [line 94]</span>;
    NULLIFY(&amp;error); [line 94];
    NULLIFY(&amp;this); [line 94];
    EXIT_SCOPE(_,n$11,n$13,n$14,error,this); [line 94];
    </span>
    .... After Symbolic Execution ....
    
    
    
  </LISTING>