<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException():v.45a2754f89c8ea8a5d2b4deeb88b1440_node4</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
body { background-color:#fff; color:#000; font-family:Helvetica, sans-serif; font-size:10pt }
h1 { font-size:14pt }
.code { border-collapse:collapse; width:100%; font-family: "Andale Mono", monospace; font-size:10pt; line-height: 1.2em }
.color_black { color: black }
.color_blue { color: blue }
.color_green { color: green }
.color_orange { color: orange }
.color_red { color: red }
.line { border-left: 3px solid #ccc; padding-left: 1ex; white-space: pre; }
.msg { background-color:#fff8b4; color:#000; float:left; font-family:Helvetica, sans-serif; font-size: smaller; font-weight: bold; margin-bottom:10px; margin-top:10px; max-width:60em; padding:0.5em 1ex 0.5em 1ex; -webkit-border-radius:5px; -webkit-box-shadow:1px 1px 7px #000; white-space: pre-wrap; word-wrap: break-word; }
.num { background-color:#eee; color:#444; font-size: smaller; padding-right:2ex; text-align:right; width:2.5em; }
.dangling { background-color:white; color: gray; }
.visited { background-color:LemonChiffon; color: darkmagenta; }
.tooltip { display: none; background-color:#FFF0F0; border: 2px solid #F00; font-weight: normal; left:10em; padding: 2px; position: absolute; top: -1em; -webkit-border-radius:5px; -webkit-box-shadow:1px 1px 7px #000; z-index: 1}
.with_tooltip { position: relative; }
.with_tooltip:hover .tooltip, .visited:hover .tooltip { display: block; }
</style>
</head>
<body>
<center><h1>Cfg Node <a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">4</a></h1></center>PROC: <a href="./../org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440.html">void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException()</a> LINE: <a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>
<br>PREDS:
<a href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node1.html"><span class='visited with_tooltip'>N_1<span class='tooltip'>node1 preds: succs:4 exn:2 </span></span></a><br>SUCCS:
<a href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node5.html"><span class='visited with_tooltip'>N_5<span class='tooltip'>node5 preds:4 succs:6 exn:3 </span></span></a><br>EXN:
<a href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node3.html"><span class='visited with_tooltip'>N_3<span class='tooltip'>node3 preds:12 succs:2 exn:2 </span></span></a><br>
<LISTING class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38];
n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38];
*&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38];
</LISTING>
<hr width="100%">
<a name="session22" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session22">node4#session22</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [compute pre] liveness 4
<LISTING class='color_black'>JOIN

LEFT:   normal:{ exception, return }, exn:{ }
RIGHT:  normal:{ }, exn:{ }
RESULT: normal:{ exception, return }, exn:{ }

</LISTING>
<hr width="100%">
<a name="session23" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session23">node4#session23</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] liveness 4
<LISTING class='color_black'>PRE STATE:
normal:{ exception, return }, exn:{ }

INSTR=  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]; 

STATE:
normal:{ n$0, return }, exn:{ }

INSTR=  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,&quot;pesto&quot;:java.lang.Object*) [line 38]; 

STATE:
normal:{ n$0, return }, exn:{ }

INSTR=  n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]; 

STATE:
normal:{ return }, exn:{ }

</LISTING>
<hr width="100%">
<a name="session27" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session27">node4#session27</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [compute pre] nullify
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session28" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session28">node4#session28</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] nullify
<LISTING class='color_black'>PRE STATE:
(normal:{ }, exn:{ },normal:{ }, exn:{ })

INSTR=  n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]; 

STATE:
(normal:{ n$0 }, exn:{ },normal:{ }, exn:{ })

INSTR=  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,&quot;pesto&quot;:java.lang.Object*) [line 38]; 

STATE:
(normal:{ n$0, n$1 }, exn:{ },normal:{ }, exn:{ })

INSTR=  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]; 

STATE:
(normal:{ exception }, exn:{ },normal:{ n$0, n$1 }, exn:{ })

</LISTING>
<hr width="100%">
<a name="session52" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session52">node4#session52</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [compute pre] devirtualizer analysis 4
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session53" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session53">node4#session53</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] devirtualizer analysis 4
<LISTING class='color_black'>PRE STATE:
{ }

INSTR=  n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]; 

STATE:
{ n$0 -&gt; org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException }

INSTR=  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,&quot;pesto&quot;:java.lang.Object*) [line 38]; 

STATE UNCHANGED

INSTR=  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]; 

STATE:
{ n$0 -&gt; org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException,
  exception -&gt; org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException }

INSTR=  EXIT_SCOPE(n$0,n$1); [line 38]; 

STATE UNCHANGED

</LISTING>
<hr width="100%">
<a name="session102" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session102">node4#session102</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session103" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session103">node4#session103</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session104" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session104">node4#session104</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session105" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session105">node4#session105</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] devirtualizer
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session2" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session2">node4#session2</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [compute pre] starvation
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session3" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session3">node4#session3</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] starvation
<LISTING class='color_black'>PRE STATE:
{guard_map= { }; lock_state= {map= { }; acquisitions= { }};
 critical_pairs= { }; attributes= { }; thread= UnknownThread;
 scheduled_work= { }; var_state= { }}

INSTR=  n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]; 

STATE UNCHANGED

INSTR=  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,&quot;pesto&quot;:java.lang.Object*) [line 38]; 

STATE:
{guard_map= { }; lock_state= {map= { }; acquisitions= { }};
 critical_pairs= { }; attributes= { }; thread= UnknownThread;
 scheduled_work= { }; var_state= { }}

INSTR=  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]; 

STATE UNCHANGED

INSTR=  EXIT_SCOPE(n$0,n$1); [line 38]; 

STATE:
{guard_map= { }; lock_state= {map= { }; acquisitions= { }};
 critical_pairs= { }; attributes= { }; thread= UnknownThread;
 scheduled_work= { }; var_state= { }}

</LISTING>
<hr width="100%">
<a name="session15" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session15">node4#session15</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [compute pre] racerd
<LISTING class='color_black'></LISTING>
<hr width="100%">
<a name="session16" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session16">node4#session16</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) [exec] racerd
<LISTING class='color_black'>PRE STATE:
Threads: NoThread, Locks: 0 
Accesses { } 
Ownership: { this -&gt; OwnedIf{ 0 } } 
Attributes: { } 


INSTR=  n$0 := __new({ sizeof(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException) }) [line 38]; 

STATE:
Threads: NoThread, Locks: 0 
Accesses { } 
Ownership: { n$0 -&gt; Owned, this -&gt; OwnedIf{ 0 } } 
Attributes: { } 


INSTR=  n$1 := MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)({ n$0,
                                                                    &quot;pesto&quot; }) [line 38]; 

STATE:
Threads: NoThread, Locks: 0 
Accesses { } 
Ownership: { n$0 -&gt; Owned, n$1 -&gt; Unowned, this -&gt; OwnedIf{ 0 } } 
Attributes: { } 


INSTR=  exception := n$0 [line 38]; 

STATE:
Threads: NoThread, Locks: 0 
Accesses { } 
Ownership: { n$0 -&gt; Owned,
             n$1 -&gt; Unowned,
             exception -&gt; Owned,
             this -&gt; OwnedIf{ 0 } } 
Attributes: { } 


INSTR=  EXIT_SCOPE(n$0,n$1); [line 38]; 

STATE UNCHANGED

</LISTING>
<hr width="100%">
<a name="session28" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session28">node4#session28</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) biabduction
<LISTING class='color_black'>**** [FP:Pending] void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException() Node: 4, Procedure: void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException(), Todo: 1 ****
  PROP 1 of 1:
  <span class='color_blue'><span class='color_red'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_red'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_red'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span>
  [footprint
     <span class='color_red'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
  .... Instructions: ....
  <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38];
  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38];
  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38];
  EXIT_SCOPE(n$0,n$1); [line 38];
  </span>
  
  Processing prop 1/1
    Instruction <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]</span>
    found array with sizeof(..) size
    converting original hpred: _t$6|->[sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)|]<span class='color_orange'>alloc</span>:char[_*1][sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)]
    into the following: _t$6|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    Found 1 specs for function org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String)
    START EXECUTING SPECS FOR org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String) from state
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    [footprint
       this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
    EXECUTING SPEC 1/1
    ACTUAL PRECONDITION =
      <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
      [footprint
         this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>message|callee = _t$12<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$14<span class='color_orange'>initial</span>:void</span></span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)
    pi2:
      
    returns
    sub1:
      
    sub2:
      
    Current Implication
    SUB:
      
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
    exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    [footprint
       this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
    |-
    <span class='color_blue'>message|callee = _t$12<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    
      do_imply "pesto" _t$12
        Current Implication
        SUB:
          
        <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
        exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
        this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
        [footprint
           this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
        [SUB: 
          _t$12 = "pesto"]
        |-
        <span class='color_blue'>this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
        
          do_imply n$0 _t$13
            Final Implication
            SUB:
              
            <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
            exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
            n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
            [footprint
               this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
            [SUB: 
              _t$12 = "pesto"; _t$13 = n$0]
            |-
            <span class='color_blue'></span>
    Result of Abduction
      SUB:
        
      <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
      [footprint
         this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
      [SUB: 
        _t$12 = "pesto"; _t$13 = n$0]
      |-
      <span class='color_blue'>message|callee = "pesto"<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = n$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    returning TRUE
      New footprint:
      
      Frame fld:
      
      Missing fld:
      
      Instantiated frame:
      n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException; &amp;exception|->n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; &amp;CatchVar25|->n$8<span class='color_orange'>initial</span>:void; &amp;return|->n$9<span class='color_orange'>initial</span>:void; &amp;errors|->n$10<span class='color_orange'>initial</span>:java.util.List*; &amp;this|->@f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;old_this|->@f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;e|->n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*
      Instantiated post:
      PROP 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$14<span class='color_orange'>initial</span>:void</span></span>
      
    ***** RESULTS FUNCTION CALL *******
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = n$8<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = n$9<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = n$10<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    ***** END RESULTS FUNCTION CALL *******
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>*&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    .... Rearrangement Start ....
    Exp: &amp;exception
    Prop:
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$12<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$13<span class='color_orange'>initial</span>:void; return = n$14<span class='color_orange'>initial</span>:void; errors = n$15<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$16<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    [footprint
       this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
    
    in prop_iter_extend_ptsto lexp: &amp;exception
    prop before:
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$12<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$13<span class='color_orange'>initial</span>:void; return = n$14<span class='color_orange'>initial</span>:void; errors = n$15<span class='color_orange'>initial</span>:java.util.List*; this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$16<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    [footprint
       this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )  ]</span>
    
    
    prop list after:
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = n$12<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = n$13<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = n$14<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = n$15<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = n$16<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    
    
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>n$0<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    Instruction <span class='color_green'>EXIT_SCOPE(n$0,n$1); [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: found exception :java.lang.Throwable*
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    .... After Symbolic Execution ....
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>update:38</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    [footprint
       <span class='color_blue'>this = @f$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>  ]</span>
    
    
    
  </LISTING>
<hr width="100%">
<a name="session45" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session45">node4#session45</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) biabduction
<LISTING class='color_black'>**** [RE:Pending] void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException() Node: 4, Procedure: void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException(), Todo: 1 ****
  PROP 1 of 1:
  <span class='color_blue'><span class='color_red'>(-1  &lt;  val$3)</span>; <span class='color_red'>val$3 != 1</span> ;
  <span class='color_red'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_red'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_red'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_red'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
  <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
  .... Instructions: ....
  <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38];
  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38];
  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38];
  EXIT_SCOPE(n$0,n$1); [line 38];
  </span>
  
  Processing prop 1/1
    Instruction <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]</span>
    found array with sizeof(..) size
    converting original hpred: _t$6|->[sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)|]<span class='color_orange'>alloc</span>:char[_*1][sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)]
    into the following: _t$6|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_red'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    Found 1 specs for function org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String)
    START EXECUTING SPECS FOR org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String) from state
    <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    EXECUTING SPEC 1/1
    ACTUAL PRECONDITION =
      <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>message|callee = _t$12<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$14<span class='color_orange'>initial</span>:void</span></span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      (-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)
    pi2:
      
    returns
    sub1:
      
    sub2:
      
    Current Implication
    SUB:
      
    <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
    exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    |-
    <span class='color_blue'>message|callee = _t$12<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    
      do_imply "pesto" _t$12
        Current Implication
        SUB:
          
        <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
        exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
        $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
        [SUB: 
          _t$12 = "pesto"]
        |-
        <span class='color_blue'>this|callee = _t$13<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
        
          do_imply n$0 _t$13
            Final Implication
            SUB:
              
            <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
            exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
            $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
            [SUB: 
              _t$12 = "pesto"; _t$13 = n$0]
            |-
            <span class='color_blue'></span>
    Result of Abduction
      SUB:
        
      <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$8<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$9<span class='color_orange'>initial</span>:void; errors = n$10<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
      [SUB: 
        _t$12 = "pesto"; _t$13 = n$0]
      |-
      <span class='color_blue'>message|callee = "pesto"<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = n$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    returning TRUE
      New footprint:
      
      Frame fld:
      
      Missing fld:
      
      Instantiated frame:
      val$2|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException; &amp;exception|->n$7<span class='color_orange'>initial</span>:java.lang.Throwable*; &amp;CatchVar25|->n$8<span class='color_orange'>initial</span>:void; &amp;$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); &amp;return|->n$9<span class='color_orange'>initial</span>:void; &amp;errors|->n$10<span class='color_orange'>initial</span>:java.util.List*; &amp;this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;old_this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;e|->n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*
      Instantiated post:
      PROP 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$14<span class='color_orange'>initial</span>:void</span></span>
      
    ***** RESULTS FUNCTION CALL *******
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = n$7<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = n$8<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = n$9<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = n$10<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = n$11<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    ***** END RESULTS FUNCTION CALL *******
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>*&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    .... Rearrangement Start ....
    Exp: &amp;exception
    Prop:
    <span class='color_blue'>(-1  &lt;  val$3); val$3 != 1; MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$12<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$13<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$14<span class='color_orange'>initial</span>:void; errors = n$15<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$16<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>n$0<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>EXIT_SCOPE(n$0,n$1); [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: found exception :java.lang.Throwable*
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    .... After Symbolic Execution ....
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(-1  &lt;  val$3)</span>; <span class='color_blue'>val$3 != 1</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>update:38</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    
    
  </LISTING>
<hr width="100%">
<a name="session58" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session58">node4#session58</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) biabduction
<LISTING class='color_black'>**** [RE:Pending] void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException() Node: 4, Procedure: void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException(), Todo: 1 ****
  PROP 1 of 1:
  <span class='color_blue'><span class='color_red'>(val$3  &lt;=  -1)</span> ;
  <span class='color_red'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_red'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_red'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_red'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
  <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
  .... Instructions: ....
  <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38];
  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38];
  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38];
  EXIT_SCOPE(n$0,n$1); [line 38];
  </span>
  
  Processing prop 1/1
    Instruction <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]</span>
    found array with sizeof(..) size
    converting original hpred: _t$194|->[sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)|]<span class='color_orange'>alloc</span>:char[_*1][sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)]
    into the following: _t$194|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>initial</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_red'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    Found 1 specs for function org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String)
    START EXECUTING SPECS FOR org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String) from state
    <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    EXECUTING SPEC 1/1
    ACTUAL PRECONDITION =
      <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>message|callee = _t$200<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$201<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$202<span class='color_orange'>initial</span>:void</span></span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      (val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)
    pi2:
      
    returns
    sub1:
      
    sub2:
      
    Current Implication
    SUB:
      
    <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
    exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    |-
    <span class='color_blue'>message|callee = _t$200<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$201<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    
      do_imply "pesto" _t$200
        Current Implication
        SUB:
          
        <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
        exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
        $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
        [SUB: 
          _t$200 = "pesto"]
        |-
        <span class='color_blue'>this|callee = _t$201<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
        
          do_imply n$0 _t$201
            Final Implication
            SUB:
              
            <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
            exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
            $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
            [SUB: 
              _t$200 = "pesto"; _t$201 = n$0]
            |-
            <span class='color_blue'></span>
    Result of Abduction
      SUB:
        
      <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$123<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$124<span class='color_orange'>initial</span>:void; errors = n$125<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
      [SUB: 
        _t$200 = "pesto"; _t$201 = n$0]
      |-
      <span class='color_blue'>message|callee = "pesto"<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = n$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    returning TRUE
      New footprint:
      
      Frame fld:
      
      Missing fld:
      
      Instantiated frame:
      val$2|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException; &amp;exception|->n$122<span class='color_orange'>initial</span>:java.lang.Throwable*; &amp;CatchVar25|->n$123<span class='color_orange'>initial</span>:void; &amp;$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); &amp;return|->n$124<span class='color_orange'>initial</span>:void; &amp;errors|->n$125<span class='color_orange'>initial</span>:java.util.List*; &amp;this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;old_this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;e|->n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*
      Instantiated post:
      PROP 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$202<span class='color_orange'>initial</span>:void</span></span>
      
    ***** RESULTS FUNCTION CALL *******
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = n$122<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = n$123<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = n$124<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = n$125<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = n$126<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    ***** END RESULTS FUNCTION CALL *******
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>*&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    .... Rearrangement Start ....
    Exp: &amp;exception
    Prop:
    <span class='color_blue'>(val$3  &lt;=  -1); MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$127<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$128<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$129<span class='color_orange'>initial</span>:void; errors = n$130<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$131<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>n$0<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>EXIT_SCOPE(n$0,n$1); [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: found exception :java.lang.Throwable*
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    .... After Symbolic Execution ....
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>(val$3  &lt;=  -1)</span>; <span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:val$3<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    
    
  </LISTING>
<hr width="100%">
<a name="session75" href="./../nodes/org.junit.tests.assertion.MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException%28%29%3Av.45a2754f89c8ea8a5d2b4deeb88b1440_node4.html#session75">node4#session75</a>(<a href="./../../MultipleFailureExceptionTest.java.5c3e6d8739a7da2006aef2128f5f1965.html#LINE38">38</a>) biabduction
<LISTING class='color_black'>**** [RE:Pending] void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException() Node: 4, Procedure: void MultipleFailureExceptionTest.assertEmptyRethrowsSingleRuntimeException(), Todo: 1 ****
  PROP 1 of 1:
  <span class='color_blue'><span class='color_red'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_red'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_red'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_red'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_red'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_red'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
  <span class='color_red'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
  .... Instructions: ....
  <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38];
  n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38];
  *&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38];
  EXIT_SCOPE(n$0,n$1); [line 38];
  </span>
  
  Processing prop 1/1
    Instruction <span class='color_green'>n$0=_fun___new(sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*) [line 38]</span>
    found array with sizeof(..) size
    converting original hpred: _t$433|->[sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)|]<span class='color_orange'>alloc</span>:char[_*1][sizeof(t=org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException)]
    into the following: _t$433|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>initial</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_red'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>n$1=_fun_MultipleFailureExceptionTest$ExpectedException.&lt;init&gt;(String)(n$0:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*,"pesto":java.lang.Object*) [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    Found 1 specs for function org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String)
    START EXECUTING SPECS FOR org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException.<init>(java.lang.String) from state
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    EXECUTING SPEC 1/1
    ACTUAL PRECONDITION =
      <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    SPEC =
      --------------------------- ---------- ---------------------------
      PRE:
      <span class='color_blue'><span class='color_blue'>message|callee = _t$439<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$440<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span></span>
      POST 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$441<span class='color_orange'>initial</span>:void</span></span>
      ----------------------------------------------------------------
    pre_check_pure_implication
    pi1:
      MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)
    pi2:
      
    returns
    sub1:
      
    sub2:
      
    Current Implication
    SUB:
      
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
    exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    |-
    <span class='color_blue'>message|callee = _t$439<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = _t$440<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    
      do_imply "pesto" _t$439
        Current Implication
        SUB:
          
        <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
        exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
        $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
        [SUB: 
          _t$439 = "pesto"]
        |-
        <span class='color_blue'>this|callee = _t$440<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
        
          do_imply n$0 _t$440
            Final Implication
            SUB:
              
            <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
            exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
            $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
            [SUB: 
              _t$439 = "pesto"; _t$440 = n$0]
            |-
            <span class='color_blue'></span>
    Result of Abduction
      SUB:
        
      <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(this|callee) ;
      exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$269<span class='color_orange'>initial</span>:void; message|callee = "pesto"<span class='color_orange'>actual_precondition</span>:java.lang.Object*; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$270<span class='color_orange'>initial</span>:void; errors = n$271<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); this|callee = n$0<span class='color_orange'>actual_precondition</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*; old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
      $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); this|callee|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
      [SUB: 
        _t$439 = "pesto"; _t$440 = n$0]
      |-
      <span class='color_blue'>message|callee = "pesto"<span class='color_orange'>formal</span>:java.lang.String*( sub ); this|callee = n$0<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*( sub )</span>
    returning TRUE
      New footprint:
      
      Frame fld:
      
      Missing fld:
      
      Instantiated frame:
      val$2|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException; &amp;exception|->n$268<span class='color_orange'>initial</span>:java.lang.Throwable*; &amp;CatchVar25|->n$269<span class='color_orange'>initial</span>:void; &amp;$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); &amp;return|->n$270<span class='color_orange'>initial</span>:void; &amp;errors|->n$271<span class='color_orange'>initial</span>:java.util.List*; &amp;this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;old_this|->val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); &amp;e|->n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*
      Instantiated post:
      PROP 1 of 1:
      <span class='color_blue'><span class='color_red'>return|callee = _t$441<span class='color_orange'>initial</span>:void</span></span>
      
    ***** RESULTS FUNCTION CALL *******
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = n$268<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = n$269<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = n$270<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = n$271<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = n$272<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    ***** END RESULTS FUNCTION CALL *******
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0)</span> ;
    <span class='color_blue'>exception = _t$4<span class='color_orange'>initial</span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>*&amp;exception:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*=n$0 [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: cannot find n$0
    .... Rearrangement Start ....
    Exp: &amp;exception
    Prop:
    <span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(n$0) ;
    exception = n$273<span class='color_orange'>initial</span>:java.lang.Throwable*; CatchVar25 = n$274<span class='color_orange'>initial</span>:void; $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub ); return = n$275<span class='color_orange'>initial</span>:void; errors = n$276<span class='color_orange'>initial</span>:java.util.List*; this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub ); e = n$277<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException* ;
    $RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub ); n$0|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>
    
    Prover.check_inconsistency_base: inconsistency reason [None]
    Prover.check_inconsistency_base: inconsistency reason [None]
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_blue'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>n$0<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span>; <span class='color_blue'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span></span>
    
    Instruction <span class='color_green'>EXIT_SCOPE(n$0,n$1); [line 38]</span>
    in vpath_find exp:n$0
    vpath_find: found exception :java.lang.Throwable*
    Instruction Returns
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = _t$3<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = _t$2<span class='color_orange'>initial</span>:void</span>; <span class='color_blue'>errors = _t$1<span class='color_orange'>initial</span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = _t$0<span class='color_orange'>initial</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    .... After Symbolic Execution ....
    PROP 1 of 1:
    <span class='color_blue'><span class='color_red'>MEMne &lt; new:38 &gt; <span class='color_orange'>{vpath: }</span>(exception)</span> ;
    <span class='color_blue'>exception = <span class='color_red'>_t$4<span class='color_orange'>update:38</span></span>:java.lang.Throwable*</span>; <span class='color_blue'>CatchVar25 = <span class='color_red'>_t$3<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar = val$2<span class='color_orange'>formal</span>:java.util.List*( sub )</span>; <span class='color_blue'>return = <span class='color_red'>_t$2<span class='color_orange'>initial</span></span>:void</span>; <span class='color_blue'>errors = <span class='color_red'>_t$1<span class='color_orange'>initial</span></span>:java.util.List*</span>; <span class='color_blue'>this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>old_this = val$1<span class='color_orange'>formal</span>:org.junit.tests.assertion.MultipleFailureExceptionTest*( sub )</span>; <span class='color_blue'>e = <span class='color_red'>_t$0<span class='color_orange'>initial</span></span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException*</span> ;
    <span class='color_red'>exception|->{}<span class='color_orange'>alloc</span>:org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException</span>; <span class='color_blue'>$RET_java.util.Collections.singletonList(org.junit.tests.assertion.MultipleFailureExceptionTest$ExpectedException):java.util.List|abducedRetvar|->{mIsEmpty:1<span class='color_orange'>formal(z)</span>}<span class='color_orange'>formal(z)</span>:java.util.List( sub )</span></span>
    
    
    
  </LISTING>